Add Guided Jacobi Iterative Solver
oneapi-src/oneAPI-samples pull request #1034
Opened 2022-08-11 17:14 UTC by IgorOchocki

# Adding a New Sample(s)

## Description

The sample is a guided Jacobi Iterative solver showcasing the benefits of a GPU and a multi GPU offload

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2022-08-11 19:25 UTC, jimmytwei commented
@tomlenth You reviewed the README with @IgorOchocki right? If so, mark it as approved.

2022-08-11 19:37 UTC, tomlenth submitted a review, later dismissed
yes, worked extensively with John and Igor.  Great sample.

2022-08-11 21:01 UTC, jimmytwei commented
@pmpeter1 Can you review this new guided Jacobi iterative solver sample? Thanks.

2022-08-23 15:44 UTC, pmpeter1 requested changes

2022-08-23 16:22 UTC, IgorOchocki commented
Updated the sample with clang formatting.

2022-08-25 16:14 UTC, pmpeter1 requested changes

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/1_guided_jacobi_iterative_solver_cpu.cpp
> +typedef double real;
should be real -> Real (it's a type).

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/1_guided_jacobi_iterative_solver_cpu.cpp
> +  for (int i = 0; i < kN; ++i) {
Can you use a more descriptibe name rather then "N" (kN).    This should be what does this represent.   N is a little too "Fortran-like" shorthand.

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/2_guided_jacobi_iterative_solver_gpu.cpp
> +typedef double real;
Should be real -> Real (its a type).

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/2_guided_jacobi_iterative_solver_gpu.cpp
> +static const int kN = 30000;
Would be better to use a more descriptive name (not kN).

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/2_guided_jacobi_iterative_solver_gpu.cpp
> +static const int kN = 30000;
The other named constants are much better in being descriptive.

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp
> +typedef double real;
Same changes for "real" and "kN".

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp
> +void GenerateMatrix(std::vector<float> &input_matrix,
Can the input matrix be a const refernce?

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp
> +    accessor M{bufin_mat, h};
Should be lower case or snake_case (nor M, R).   Also not descriptive enough.

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp
> +void PrintMatrix(std::vector<float> input_matrix,
Should input_matrix be const reference?

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp
> +void PrintResults(std::vector<real> data, int N) {
Should data be const reference?

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp
> +            accessor D{bufout_data, h};
D, OV, M, R should follow variable name conventions and be a little more descriptive.

2022-08-25 16:14 UTC, pmpeter1 commented on DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp
> +            accessor D{bufout_data, h};
Same for D. OV, M, R.     This are not idiomatic like "id" or "i", "j", "k" (loop counters).

2022-08-25 17:03 UTC, pmpeter1 approved these changes

2022-08-25 17:09 UTC, merged