Add simulator targets to several FPGA Tutorials
oneapi-src/oneAPI-samples pull request #1100
Opened 2022-09-21 20:55 UTC by ajaykumarkannan

# Existing Sample Changes
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes Issue# 

## External Dependencies

List any external dependencies created as a result of this change.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

**_Delete this line and everything below if this is not a PR for a new code sample_**

**_Delete this line and all above it if this PR is for a new code sample_**
# Adding a New Sample(s)

## Description

Please include a description of the sample

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2022-09-30 06:46 UTC, yuguen-intel requested changes

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/README.md
> +| OS                                | Linux*Ubuntu* 18.04/20.04 <br> RHEL*/CentOS* 8 <br> SUSE*15 <br> Windows* 10
Was this change intended?

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/README.md
> +     make fpga_sim
This is out of order

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/README.md
>  2. Run the sample on the FPGA device:
```suggestion
2. Run the sample on the FPGA simulator device:
```

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/README.md
> +| OS                                | CentOS*Linux 8 <br> Red Hat* Enterprise Linux*8 <br> SUSE* Linux Enterprise Server 15 <br> Ubuntu*18.04 LTS <br> Ubuntu 20.04 <br>Windows* 10
Is this intended?

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_int/README.md
> +| OS                                | Linux*Ubuntu* 18.04/20.04 <br> RHEL*/CentOS* 8 <br> SUSE*15 <br> Windows* 10
Intended?

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/README.md
> +| OS                                | Linux*Ubuntu* 18.04/20.04 <br> RHEL*/CentOS* 8 <br> SUSE*15 <br> Windows* 10
Intended?

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental/latency_control/README.md
> +| OS                                | Linux*Ubuntu* 18.04/20.04 <br> RHEL*/CentOS* 8 <br> SUSE*15 <br> Windows* 10
Intended?

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental/latency_control/README.md
>  2. Run the sample on the FPGA device:
```suggestion
2. Run the sample on the FPGA simulator device:
```

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/fpga_reg/README.md
> +| OS                                | Linux*Ubuntu* 18.04/20.04 <br> RHEL*/CentOS* 8 <br> SUSE*15 <br> Windows* 10
Intended?

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/README.md
> +| OS                                | Linux*Ubuntu* 18.04/20.04 <br> RHEL*/CentOS* 8 <br> SUSE*15 <br> Windows* 10
Intended?

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/README.md
> +   - Compile for simulation (fast compile time, targets simulated FPGA device)
Just for consistency, let's have emulation -> report -> simulation -> hw

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/README.md
> +   - Compile for the simulation target (fast compile time, targets simulated FPGA device)
Same comment about the order

2022-09-30 06:46 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/scheduler_target_fmax/README.md
> +| OS                                | Linux*Ubuntu* 18.04/20.04 <br> RHEL*/CentOS* 8 <br> SUSE*15 <br> Windows* 10
Intended?

2022-09-30 07:18 UTC, yuguen-intel commented
Please use the `target` instead of `board` in the newly added cmake commands to transition nicely with: https://github.com/oneapi-src/oneAPI-samples/pull/1111/files

2022-10-05 21:35 UTC, ajaykumarkannan commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/README.md
> +| OS                                | Linux*Ubuntu* 18.04/20.04 <br> RHEL*/CentOS* 8 <br> SUSE*15 <br> Windows* 10
Nope, typo.

2022-10-05 21:49 UTC, ajaykumarkannan commented
> Please use the `target` instead of `board` in the newly added cmake commands to transition nicely with #1111

I merged the changes from there - will submit #1111 first before this one.

2022-10-10 07:42 UTC, yuguen-intel approved these changes

2022-10-10 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/README.md
> +     make fpga_sim
Wow I did not even know about this sample.
We don't even test it :/
Paul is working on a similar but up to date sample, I'll ask for it to be replaced + moved to the FPGA part of the code samples.

2022-10-20 15:27 UTC, ajaykumarkannan commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/decompress/src/CMakeLists.txt
> +    set(CONSTEXPR_STEPS "/constexpr:steps5084968")
Is there a typo on this line?

2022-10-21 07:31 UTC, yuguen-intel requested changes

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/src/CMakeLists.txt
>  set(SOURCE_FILE main.cpp)
I'm not looking into this file too much as we are going to remove this sample entirely for this release.
After you pointed me to it, I looked at it and realized it was:
1/ outdated
2/ in a place where FPGA users would not find it

Paul will be adding a replacement to this sample in DPC++FPGA/Tutorial/GettingStarted

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_fixed/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
```

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
```

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/ac_int/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET} ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET} ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
```

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
```

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental/latency_control/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../../include)
```

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/fpga_reg/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
```

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/fpga_reg/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET_REG} EXCLUDE_FROM_ALL ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET_REG} EXCLUDE_FROM_ALL ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET_REG} PRIVATE ../../../../include)
```

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
```

2022-10-21 07:31 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/scheduler_target_fmax/src/CMakeLists.txt
> +add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
```suggestion
add_executable(${SIMULATOR_TARGET} EXCLUDE_FROM_ALL ${SOURCE_FILE})
target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
```

2022-10-21 16:28 UTC, yuguen-intel approved these changes

2022-10-21 16:28 UTC, merged