Added sim support
oneapi-src/oneAPI-samples pull request #1113
Opened 2022-10-03 21:19 UTC by artemrad

# Existing Sample Changes
## Description

Added simulator support to some tests

## External Dependencies
Dependent on the simulator

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

2022-10-24 21:00 UTC, artemrad commented
Tested: 
Linux: 
kernel_args_restrict: https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/633435632
mem_channel: https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/633395696
lsu_contrsol: https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/633343364

Windows: 
kernel_args_restrict: https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/634342459
mem_channel: https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/634322172
lsu_contrsol: https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/634225660

2022-10-24 21:30 UTC, artemrad commented
@yuguen-intel  please review.

2022-10-25 07:42 UTC, yuguen-intel requested changes
A few small changes, you can just edit a reping me so that I merge this change

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/CMakeLists.txt
> +set(SIMULATOR_LINK_FLAGS "-fsycl -fintelfpga -Xssimulation -Xstarget=${FPGA_DEVICE} ${USER_SIMULATOR_FLAGS}")
Please use the USER_HARDWARE_FLAGS for both the simulation and HW

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/CMakeLists.txt
> +#    dpcpp -fintelfpga -Xssimulation -DFPGA_SIMULATOR kernel_args_restrict.cpp -o kernel_args_restrict.fpga_sim
```suggestion
#    icpx -fsycl -fintelfpga -Xssimulation -DFPGA_SIMULATOR kernel_args_restrict.cpp -o kernel_args_restrict.fpga_sim
```

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/CMakeLists.txt
> +#    [compile] dpcpp -fintelfpga -Xssimulation -DFPGA_SIMULATOR -o kernel_args_restrict.cpp.o -c kernel_args_restrict.cpp
```suggestion
#    [compile] icpx -fsycl -fintelfpga -Xssimulation -DFPGA_SIMULATOR -o kernel_args_restrict.cpp.o -c kernel_args_restrict.cpp
```

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/CMakeLists.txt
> +#    [link]    dpcpp -fintelfpga -Xssimulation  kernel_args_restrict.cpp.o -o kernel_args_restrict.fpga_sim
```suggestion
#    [link]    icpx -fsycl -fintelfpga -Xssimulation  kernel_args_restrict.cpp.o -o kernel_args_restrict.fpga_sim
```

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/lsu_control/src/CMakeLists.txt
> +#    dpcpp -fintelfpga -Xssimulation -DFPGA_SIMULATOR lsu_control.cpp -o lsu_control.fpga_sim
```suggestion
#    icpx -fsycl -fintelfpga -Xssimulation -DFPGA_SIMULATOR lsu_control.cpp -o lsu_control.fpga_sim
```

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/lsu_control/src/CMakeLists.txt
> +#    [compile] dpcpp -fintelfpga -Xssimulation -DFPGA_SIMULATOR -o lsu_control.cpp.o -c lsu_control.cpp
```suggestion
#    [compile] icpx -fsycl -fintelfpga -Xssimulation -DFPGA_SIMULATOR -o lsu_control.cpp.o -c lsu_control.cpp
```

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/lsu_control/src/CMakeLists.txt
> +#    [link]    dpcpp -fintelfpga -Xssimulation  lsu_control.cpp.o -o lsu_control.fpga_sim
```suggestion
#    [link]    icpx -fsycl -fintelfpga -Xssimulation  lsu_control.cpp.o -o lsu_control.fpga_sim
```

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/lsu_control/src/CMakeLists.txt
> +# use cmake -D USER_SIMULATOR_FLAGS=<flags> to set extra flags for FPGA simulator compilation
Please use USER_HARDWARE_FLAGS for both simulation and HW

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/mem_channel/src/CMakeLists.txt
> +# use cmake -D USER_SIMULATOR_FLAGS=<flags> to set extra flags for FPGA simulator compilation
Please use USER_HARDWARE_FLAGS for both simulation and HW

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/mem_channel/src/CMakeLists.txt
> +#    dpcpp -fintelfpga -Xssimulation -DFPGA_SIMULATOR mem_channel.cpp -o mem_channel.fpga_sim
```suggestion
#    icpx -fsycl -fintelfpga -Xssimulation -DFPGA_SIMULATOR mem_channel.cpp -o mem_channel.fpga_sim
```

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/mem_channel/src/CMakeLists.txt
> +#    [compile] dpcpp -fintelfpga -Xssimulation -DFPGA_SIMULATOR -o mem_channel.cpp.o -c mem_channel.cpp
```suggestion
#    [compile] icpx -fsycl -fintelfpga -Xssimulation -DFPGA_SIMULATOR -o mem_channel.cpp.o -c mem_channel.cpp
```

2022-10-25 07:42 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/mem_channel/src/CMakeLists.txt
> +#    [link]    dpcpp -fintelfpga -Xssimulation  mem_channel.cpp.o -o mem_channel.fpga_sim
```suggestion
#    [link]    icpx -fsycl -fintelfpga -Xssimulation  mem_channel.cpp.o -o mem_channel.fpga_sim
```

2022-10-25 14:39 UTC, yuguen-intel requested changes

2022-10-25 14:39 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/CMakeLists.txt
>  # use cmake -D USER_SIMULATOR_FLAGS=<flags> to set extra flags for FPGA simulator compilation
You forgot to remove this comment in the three CMakeLists

2022-10-25 14:42 UTC, artemrad commented on DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/CMakeLists.txt
> +# use cmake -D USER_SIMULATOR_FLAGS=<flags> to set extra flags for FPGA simulator compilation
```suggestion
# use cmake -D USER_HARDWARE_FLAGS=<flags> to set extra flags for FPGA simulator compilation
```

2022-10-25 14:42 UTC, artemrad commented on DirectProgramming/DPC++FPGA/Tutorials/Features/lsu_control/src/CMakeLists.txt
> +# use cmake -D USER_SIMULATOR_FLAGS=<flags> to set extra flags for FPGA simulator compilation
```suggestion
# use cmake -D USER_HARDWARE_FLAGS=<flags> to set extra flags for FPGA simulator compilation
```

2022-10-25 14:42 UTC, artemrad commented on DirectProgramming/DPC++FPGA/Tutorials/Features/mem_channel/src/CMakeLists.txt
> +# use cmake -D USER_SIMULATOR_FLAGS=<flags> to set extra flags for FPGA simulator compilation
```suggestion
# use cmake -D USER_HARDWARE_FLAGS=<flags> to set extra flags for FPGA simulator compilation
```

2022-10-25 14:43 UTC, yuguen-intel approved these changes

2022-10-25 14:44 UTC, merged