Simulation support: read_only_cache and onchip_memory_cache
oneapi-src/oneAPI-samples pull request #1195
Opened 2022-11-08 17:32 UTC by artemrad

# Existing Sample Changes
## Description

Added Sim support

## Type of change
- [X ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [X ] Command Line

2022-11-08 17:37 UTC, artemrad commented
Testing Linux:
* onchip_memory_cache:  https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/635667787
* read_only_cache:  https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/640203799

Testing Windows:
* onchip_memory_cache:  https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/636032931
* read_only_cache:  https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/640215885

2022-11-09 09:04 UTC, yuguen-intel requested changes

2022-11-09 09:04 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/onchip_memory_cache/src/CMakeLists.txt
> +target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
This line is written twice

2022-11-09 09:04 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/src/CMakeLists.txt
> +add_custom_target(fpga_sim DEPENDS ${SIMULATOR_TARGET} ${SIMULATOR_TARGET})
```suggestion
add_custom_target(fpga_sim DEPENDS ${SIMULATOR_TARGET})
```

2022-11-09 15:48 UTC, artemrad commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/onchip_memory_cache/src/CMakeLists.txt
> +target_include_directories(${SIMULATOR_TARGET} PRIVATE ../../../../include)
```suggestion
```

2022-11-09 15:52 UTC, yuguen-intel approved these changes

2022-11-09 15:52 UTC, merged