Update fpga autorun readme
oneapi-src/oneAPI-samples pull request #1219
Opened 2022-11-21 15:52 UTC by jkinsky

# Existing Sample Changes
## Description

Restructured the readme to match the new template. Updated formatting. Updated some branding. Corrected some spelling and grammar. Moved images into /images folder to help clean up top-level folder.

Fixes Issue# 

## External Dependencies

N/A

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] Documentation

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [x] VSCode

2022-11-21 15:56 UTC, jkinsky commented
Adding @jimmytwei for notices.

2022-11-21 16:29 UTC, yuguen-intel commented
Interestingly I made the same kind of changes to put images in a specific folder for the reference designs.
I tried to check if there was a commonly used name for this folder in other GitHub repos and I found multiple using the name "assets" rather than "images". 
So I used that (here https://github.com/oneapi-src/oneAPI-samples/pull/1208) 
We should keep this consistent, would you be happy about using the "assets" name?

2022-11-21 16:32 UTC, yuguen-intel requested changes

2022-11-21 16:32 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/README.md
> +   cmake .. -DFPGA_BOARD=intel_s10sx_pac:pac_s10
```suggestion
   cmake .. -DFPGA_DEVICE=intel_s10sx_pac:pac_s10
```
FPGA_DEVICE here is the expected name to be used

2022-11-21 16:32 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/README.md
> +   cmake -G "NMake Makefiles" .. -DFPGA_BOARD=intel_s10sx_pac:pac_s10
Same remark

2022-11-21 16:32 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/README.md
> +   cmake -G "NMake Makefiles" .. -DFPGA_BOARD=intel_s10sx_pac:pac_s10
```suggestion
   cmake -G "NMake Makefiles" .. -DFPGA_DEVICE=intel_s10sx_pac:pac_s10
```

2022-11-21 21:31 UTC, jkinsky commented
> Interestingly I made the same kind of changes to put images in a specific folder for the reference designs. I tried to check if there was a commonly used name for this folder in other GitHub repos and I found multiple using the name "assets" rather than "images". So I used that (here #1208) We should keep this consistent, would you be happy about using the "assets" name?

I think it makes little difference what the directory is named. You can find instances of /images plus others sub-directories. I think assets might be too generic, but I really don't care that much. The main thing I hoped to accomplish was to remove visual clutters from the top-level directory.

2022-11-22 08:30 UTC, yuguen-intel commented
I completely agree that is visually makes things simpler, which is a good thing, I just want all the FPGA samples to be consistent :)

2022-11-29 18:10 UTC, jkinsky commented
Amended a commit. I might have amended the wrong commit. I'm confused over what should be a relatively simple change. Sorry I started the process.

2022-11-29 18:14 UTC, ishaghosh27 approved these changes

2022-11-30 08:53 UTC, yuguen-intel approved these changes

2022-11-30 08:53 UTC, merged