Add device_glonal test for FPGAs
oneapi-src/oneAPI-samples pull request #1291
Opened 2023-01-11 18:15 UTC by artemrad

Showcasing the device_global capabilities that users can explore in 2023.1 release

Testing: TBD

2023-01-13 20:47 UTC, artemrad commented
Linux: https://spetc.intel.com/testsummary?trview=0&testRunIds=7435850

2023-01-20 08:16 UTC, yuguen-intel requested changes
A few modifications to match the current samples expectations

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +| Time to complete                  | 15 minutes
This part has been changed in the latest code samples to split this table in two and add a "prerequisite" section.
See https://github.com/oneapi-src/oneAPI-samples/tree/development/DirectProgramming/C%2B%2BSYCL_FPGA/Tutorials/DesignPatterns/autorun for example.

To fill this prerequisite section correctly, you need to register your new sample in the `/DirectProgramming/C++SYCL_FPGA/README.md` file

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +- [Intel&reg; oneAPI Programming Guide](https://software.intel.com/en-us/oneapi-programming-guide) helps you understand target-independent, SYCL-compliant programming using Intel&reg; oneAPI Toolkits
Please remove this section

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +>For more information on environment variables, see **Use the setvars Script** for [Linux or macOS](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/oneapi-d
```suggestion
> **Note**: When working with the command-line interface (CLI), you should configure the oneAPI toolkits using environment variables. 
> Set up your CLI environment by sourcing the `setvars` script located in the root of your oneAPI installation every time you open a new terminal window. 
> This practice ensures that your compiler, libraries, and tools are ready for development.
>
> Linux*:
> - For system wide installations: `. /opt/intel/oneapi/setvars.sh`
> - For private installations: ` . ~/intel/oneapi/setvars.sh`
> - For non-POSIX shells, like csh, use the following command: `bash -c 'source <install-dir>/setvars.sh ; exec csh'`
>
> Windows*:
> - `C:\Program Files(x86)\Intel\oneAPI\setvars.bat`
> - Windows PowerShell*, use the following command: `cmd.exe "/K" '"C:\Program Files (x86)\Intel\oneAPI\setvars.bat" && powershell'`
>
> For more information on configuring environment variables, see [Use the setvars Script with Linux* or macOS*](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/oneapi-development-environment-setup/use-the-setvars-script-with-linux-or-macos.html) or [Use the setvars Script with Windows*](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/oneapi-development-environment-setup/use-the-setvars-script-with-windows.html).
```

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +[Using Visual Studio Code with Intel&reg; oneAPI Toolkits User Guide](https://www.intel.com/content/www/us/en/develop/documentation/using-vs-code-with-intel-oneapi/top.html).
Remove these sections

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +>For more information on environment variables, see **Use the setvars Script** for [Linux or macOS](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/oneapi-d
Please use this new template for the CLI env variable

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +You can compile and run this tutorial in the Eclipse* IDE (in Linux*) and the Visual Studio* IDE (in Windows*). For instructions, refer to the following link: [FPGA Workflows on Third-Party IDEs for
Please remove these sections

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +     ```
```suggestion
    * On Linux
        ```bash
        CL_CONTEXT_MPSIM_DEVICE_INTELFPGA=1 ./device_global.fpga_sim
        ```
    * On Windows
        ```bash
        set CL_CONTEXT_MPSIM_DEVICE_INTELFPGA=1
        device_global.fpga_sim.exe
        set CL_CONTEXT_MPSIM_DEVICE_INTELFPGA=
        ```
```

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/sample.json
> +          "cd ../../..",
```suggestion
          "cd ../../../..",
```

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/sample.json
> +          "cd ../../..",
```suggestion
          "cd ../../../..",
```

2023-01-20 08:16 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/device_global.cpp
> +                  sycl::property::queue::enable_profiling{});
```suggestion
    sycl::queue q(selector, fpga_tools::exception_handler,
                  sycl::property::queue::enable_profiling{});

    auto device = q.get_device();

    std::cout << "Running on device: "
              << device.get_info<sycl::info::device::name>().c_str()
              << std::endl;                  
                  
```

2023-01-23 09:44 UTC, yuguen-intel requested changes

2023-01-23 09:44 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/README.md
> +| [device_global (experimental)](Tutorials/Features/experimental/device_global)| [Tutorials/Features](Tutorials/Features)             | The basic usage of the `device_global` class <br> How to initia
```suggestion
| [device_global (experimental)](Tutorials/Features/experimental/device_global)| [Tutorials/Features](Tutorials/Features)             | The basic usage of the `device_global` class <br> How to initialize a `device_global` to non-zero values

```

2023-01-23 09:44 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +# `device_global`
```suggestion
# `device_global` Sample
```

2023-01-23 15:19 UTC, yuguen-intel approved these changes

2023-01-24 19:09 UTC, tomlenth approved these changes
Thanks, super thorough

2023-01-24 19:25 UTC, jkinsky approved these changes
There are some issues to correct, but overall this looks good for the first iteration.

2023-01-26 13:54 UTC, yuguen-intel commented
Please incorporate these changes in your PR: https://github.com/oneapi-src/oneAPI-samples/pull/1307

2023-01-27 08:53 UTC, yuguen-intel requested changes

2023-01-27 08:53 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt
> +    set(IS_BSP "0")
```suggestion
```

2023-01-27 08:53 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt
> +    message(STATUS "Configuring the design with the following target: ${FPGA_DEVICE}")
```suggestion
    string(TOLOWER ${FPGA_DEVICE} FPGA_DEVICE_NAME)
    if(FPGA_DEVICE_NAME MATCHES ".*a10.*" OR FPGA_DEVICE_NAME MATCHES ".*arria10.*")
      set(DEVICE_FLAG "A10")
    elseif(FPGA_DEVICE_NAME MATCHES ".*s10.*" OR FPGA_DEVICE_NAME MATCHES ".*stratix10.*")
      set(DEVICE_FLAG "S10")
    elseif(FPGA_DEVICE_NAME MATCHES ".*agilex.*")
      set(DEVICE_FLAG "Agilex")
    endif()
    message(STATUS "Configuring the design with the following target: ${FPGA_DEVICE}")
```

2023-01-27 08:53 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt
> +    endif()
```suggestion
```

2023-01-27 08:53 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt
```suggestion

if(NOT DEFINED DEVICE_FLAG)
    message(FATAL_ERROR "An unrecognized or custom board was passed, but DEVICE_FLAG was not specified. \
                         Make sure you have set -DDEVICE_FLAG=A10, -DDEVICE_FLAG=S10 or -DDEVICE_FLAG=Agilex.")
endif()

```

2023-01-27 08:53 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt
And 
`if(FPGA_DEVICE MATCHES ".*a10.*")`
need to be modified to 
`if(DEVICE_FLAG MATCHES "A10")`

2023-01-27 16:07 UTC, pmpeter1 approved these changes

2023-01-27 17:49 UTC, artemrad commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +
```suggestion
```

2023-01-27 17:49 UTC, artemrad commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md
> +3. (Optional) As the FPGA hardware compile may take several hours to complete, FPGA precompiled binaries (compatible with Linux* Ubuntu* 18.04) can be downloaded <a href="https://iotdk.intel.com/fpga
```suggestion
```

2023-01-27 17:52 UTC, artemrad commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt
> +if(FPGA_DEVICE MATCHES ".*a10.*")
```suggestion
if(FPGA_DEVICE MATCHES ".*A10.*")
```

2023-01-27 17:54 UTC, yuguen-intel requested changes

2023-01-27 17:54 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt
> +if(FPGA_DEVICE MATCHES ".*A10.*")
```suggestion
if(DEVICE_FLAG MATCHES "A10")
```

2023-01-27 17:55 UTC, artemrad commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt
> +    elseif(FPGA_DEVICE_NAME MATCHES ".*S10.*" OR FPGA_DEVICE_NAME MATCHES ".*stratix10.*")
```suggestion
    if(FPGA_DEVICE_NAME MATCHES ".*a10.*" OR FPGA_DEVICE_NAME MATCHES ".*arria10.*")
      set(DEVICE_FLAG "A10")
    elseif(FPGA_DEVICE_NAME MATCHES ".*a10.*" OR FPGA_DEVICE_NAME MATCHES ".*stratix10.*")
```

2023-01-27 17:56 UTC, yuguen-intel approved these changes

2023-01-30 08:59 UTC, merged