Private copies2
oneapi-src/oneAPI-samples pull request #1296
Opened 2023-01-13 17:40 UTC by artemrad

Added Sim support

Tests: TBD

2023-01-13 20:03 UTC, artemrad commented
Linux: https://spetc.intel.com/testsummary?trview=0&testRunIds=7436513

2023-01-16 08:08 UTC, yuguen-intel requested changes

2023-01-16 08:08 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/private_copies/README.md
> +     ```
With the new selectors, one must run the sim executable with a specific env variable.
See the instructions in another sample (e.g. https://github.com/oneapi-src/oneAPI-samples/tree/development/DirectProgramming/C%2B%2BSYCL_FPGA/Tutorials/GettingStarted/fpga_compile) and update the instructions here

2023-01-16 16:48 UTC, yuguen-intel approved these changes

2023-01-16 16:49 UTC, merged