[FPGA] create new invocation interfaces sample
oneapi-src/oneAPI-samples pull request #1303
Opened 2023-01-18 15:36 UTC by intel-jisheng1

# Adding a New Sample(s)

## Description

This new FPGA tutorial shows how to specify the kernel invocation interfaces and kernel argument interfaces that will be generated in RTL in the FPGA IP-Authoring flow. The kernel invocation interface (namely, the start and done signals) can be implemented in the kernel's CSR, or using a ready/valid handshake. Similarly, the kernel arguments can be passed through the CSR, or through dedicated conduits.

## Checklist
Administrative
- [x] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [x] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [x] Adhere to readme template 
- [x] Enforce format via clang-format config file
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [x] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [x] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2023-01-18 16:08 UTC, yuguen-intel approved these changes

2023-01-26 13:55 UTC, yuguen-intel commented
Please incorporate these changes in your PR: https://github.com/oneapi-src/oneAPI-samples/pull/1307

2023-01-30 15:42 UTC, yuguen-intel approved these changes

2023-02-03 16:24 UTC, pmpeter1 approved these changes

2023-02-03 19:51 UTC, tomlenth requested changes
please add the expertise to the json.  I believe it should be:   "expertise": "Concepts and Functionality"

2023-02-03 20:20 UTC, intel-jisheng1 commented
> please add the expertise to the json. I believe it should be: "expertise": "Concepts and Functionality"

Added.

2023-02-03 20:30 UTC, jkinsky approved these changes

2023-02-06 22:14 UTC, tomlenth approved these changes

2023-02-07 08:51 UTC, merged