Introduction to Machine Learning readme update
oneapi-src/oneAPI-samples pull request #1732
Opened 2023-06-15 19:18 UTC by jkinsky

# Existing Sample Changes
## Description

Restructured to match new template-as much as possible. Updated multiple branding and legal issues. Updated some copy for clarity and to correct spelling errors. Corrected formatting issues. Rearranged some sections to match new template structure as much as possible. Added prerequisites information. Expanded information on using samples locally and in DevCloud. Corrected spelling error and branding issues in sample.json description. (Did not update any readme files in subdirectories.)

Fixes Issue# 

## External Dependencies

N/A

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] Documentation

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] VSCode

2023-06-16 19:46 UTC, tomlenth requested changes
Can we get expertise added in for tutorial.  looks like some of the others in this part of the repo are tagged tutorial.

2023-06-21 15:03 UTC, jimmytwei commented
> Can we get expertise added in for tutorial. looks like some of the others in this part of the repo are tagged tutorial.

@tomlenth Looks like tutorial has been added as expertise.

2023-06-21 15:03 UTC, jimmytwei approved these changes

2023-06-21 21:58 UTC, tomlenth approved these changes

2023-06-23 15:53 UTC, merged