updated the simplified version of the accessors, used auto for parallel…
oneapi-src/oneAPI-samples pull request #181
Opened 2020-09-25 20:23 UTC by praveenkk123

updated the simplifed version of the accessors, used "auto" for the parallel_for index as per the coding guidelines

index

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue) 

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [ ] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [ ] Implement coding guidelines and ensure code quality.
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [ ] Adhere to readme template 
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Enforce format via clang-format config file
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [ ] Tested using Dev Cloud when applicable
- [ ] Implement fixes for ONSAM Jiras
- [ ] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

2020-09-25 20:55 UTC, pmpeter1 requested changes
The edits to simplify with Beta09 syntax look good.      In reviewing more, I noticed a strange usage of "num_elements" in the compute functions.    This is a global constant used to initialize the vectors.

The question is that this should not be used by the compute functions.   Instead you can get the right info from the size of the vectors passed into the function.      To avoid errors, you can also verify that the size of the two vectors passed in are the same.  This makes all of the logic inside of the compute functions to local to the functions and the arguments that are passed into the function.

2020-09-25 21:19 UTC, anjgola submitted a review, later dismissed

2020-09-25 21:51 UTC, pmpeter1 requested changes
Typo in error messages *didnt*, better to spell out as *do not*

Should also check out_vect to make sure it's also the same size.

2020-09-25 23:52 UTC, pmpeter1 approved these changes

2020-09-28 20:57 UTC, JoeOster requested changes
A couple of things 

1. Please add comment to Readme in regards to location of dpc_common.hpp, should look like this:

> 
> Building the Program for CPU and GPU
> Include Files
> The include folder is located at %ONEAPI_ROOT%\dev-utilities\latest\include on your development system.
> 
> as seen in https://github.com/oneapi-src/oneAPI-samples/tree/master/DirectProgramming/DPC%2B%2B/CombinationalLogic/sepia-filter
> 


2. Please add the comments below for the include of dpc_common.hp. it should look like this:

> // dpc_common.hpp can be found in the dev-utilities include folder.
> // e.g., $ONEAPI_ROOT/dev-utilities/<version>/include/dpc_common.hpp
> #include "dpc_common.hpp"
> 
> as seen in https://github.com/oneapi-src/oneAPI-samples/blob/master/DirectProgramming/DPC%2B%2B/CombinationalLogic/mandelbrot/src/main.cpp
> 
>

2020-09-28 23:20 UTC, JoeOster approved these changes

2020-09-29 14:52 UTC, merged