FPGA: Add sample for streaming data interfaces with pipes
oneapi-src/oneAPI-samples pull request #1863
Opened 2023-08-30 15:13 UTC by williamwang256

# Adding a New Sample(s)

## Description

A new sample demonstrating how to use pipes to implement streaming data interfaces on IP components.

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2023-08-31 12:55 UTC, yuguen-intel approved these changes

2023-09-01 08:07 UTC, yuguen-intel requested changes

2023-09-01 08:07 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/streaming_data_interfaces/CMakeLists.txt
> +# folder.
```suggestion
# Use cmake -DFPGA_DEVICE=<board-support-package>:<board-variant> to choose a
# different device. 
# Note that depending on your installation, you may need to specify the full 
# path to the board support package (BSP), this usually is in your install 
# folder.
```
Removing mentions to PAC boards

2023-09-04 14:32 UTC, yuguen-intel approved these changes

2023-09-06 15:25 UTC, pmpeter1 requested changes

2023-09-07 06:11 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/streaming_data_interfaces/src/streaming_data_interfaces.cpp
> +#define THRESHOLD 200
```suggestion
constexpr int kThreshold = 200;
```

2023-09-07 06:11 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/streaming_data_interfaces/src/streaming_data_interfaces.cpp
> +        pixel = THRESHOLD;
```suggestion
      if (pixel > kThreshold)
        pixel = kThreshold;
```

2023-09-07 06:11 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/streaming_data_interfaces/src/streaming_data_interfaces.cpp
> +      passed &= (out_beat.data <= THRESHOLD);
```suggestion
      passed &= (out_beat.data <= kThreshold);
```

2023-09-07 06:12 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/streaming_data_interfaces/src/streaming_data_interfaces.cpp
> +#define THRESHOLD 200
Now addressed.

2023-09-11 22:21 UTC, ishaghosh27 approved these changes

2023-09-12 08:34 UTC, merged