Removed Python2.7, renamed daal4py samples and related files
oneapi-src/oneAPI-samples pull request #187
Opened 2020-09-28 15:25 UTC by raoberman

# Description

Removed Python2.7 dependency (request), renamed daal4py samples and related files

Fixes # internal email issue

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [X] DevCloud

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [X] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [X] Implement coding guidelines and ensure code quality.
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [X] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [X] Adhere to readme template 
- [X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [X] Enforce format via clang-format config file
- [X] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [X] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [X] Tested using Dev Cloud when applicable
- [X] Implement fixes for ONSAM Jiras
- [X] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

2020-09-28 15:30 UTC, raoberman commented
@JoeOster please note Python 2.7 removal on README.

2020-09-28 15:43 UTC, JoeOster submitted a review, later dismissed

2020-09-29 14:53 UTC, anjgola approved these changes
Run tests.

2020-09-29 21:03 UTC, JoeOster approved these changes

2020-10-01 14:46 UTC, raoberman commented
@JoeOster (or Tom) please review Intel_Modin_GS and IntelPython_XGBoost_GS sample README.mds in Frameworks folder

2020-10-01 15:20 UTC, JoeOster requested changes

2020-10-01 15:20 UTC, JoeOster commented on Libraries/oneDAL/IntelPython_daal4py_Distributed_LinearRegression/License.txt
> +Copyright Intel Corporation
Please change the text of the license file to the one [here](https://github.com/oneapi-src/oneAPI-samples/blob/master/License.txt)

2020-10-01 15:20 UTC, JoeOster commented on Libraries/oneDAL/IntelPython_daal4py_Getting_Started/License.txt
> +
Please change the text of the license file to the one [here](https://github.com/oneapi-src/oneAPI-samples/blob/master/License.txt)

2020-10-01 15:20 UTC, JoeOster commented on Libraries/oneDAL/IntelPython_daal4py_Distributed_LinearRegression/README.md
> -# daal4py Distributed Linear Regression
Old styleReadme, please update using the [mandelbrot readme](https://github.com/oneapi-src/oneAPI-samples/blob/master/DirectProgramming/DPC%2B%2B/CombinationalLogic/mandelbrot/README.md) as an example: In this case a "Purpose" and "License" sections are missing at a minimum

2020-10-01 15:20 UTC, JoeOster commented on Libraries/oneDAL/IntelPython_daal4py_Distributed_Kmeans/README.md
> -# daal4py Distributed K-Means
Old styleReadme, please update using the [mandelbrot readme](https://github.com/oneapi-src/oneAPI-samples/blob/master/DirectProgramming/DPC%2B%2B/CombinationalLogic/mandelbrot/README.md) as an example: In this case a "Purpose" and "License" sections are missing at a minimum

2020-10-01 15:20 UTC, JoeOster commented on Frameworks/IntelPython_XGBoost/IntelPython_XGBoost_GettingStarted/README.md
> +# Intel Python XGBoost Getting Started
Old styleReadme, please update using the [mandelbrot readme](https://github.com/oneapi-src/oneAPI-samples/blob/master/DirectProgramming/DPC%2B%2B/CombinationalLogic/mandelbrot/README.md) as an example: In this case a "Purpose" and "License" sections are missing at a minimum

2020-10-01 15:23 UTC, raoberman commented on Libraries/oneDAL/IntelPython_daal4py_Getting_Started/README.md
> -# daal4py Getting Started
Joe, Not sure which ReadMe you are looking at (daal4py sample renamed). This was fixed in beta09 PR, seenew README which has purpose and license: https://github.com/raoberman/oneAPI-samples/tree/master/Libraries/oneDAL/IntelPython_daal4py_Getting_Started

2020-10-01 15:45 UTC, JoeOster submitted a review, later dismissed

2020-10-01 20:46 UTC, tomlenth commented
In XGBoost,  the image in Running the Sample says "Modin_GettingStarted".  should it be XGBoost?

2020-10-01 20:51 UTC, raoberman commented
@tomlenth Modin GettingStarted image is used just as example (also says so in README)- same logic applies for XGBoost sample

2020-10-01 20:51 UTC, JoeOster submitted a review, later dismissed

2020-10-01 20:56 UTC, tomlenth approved these changes

2020-10-05 16:52 UTC, raoberman commented
@anjgola @JoeOster  the Modin test continues to fail because of no current environments have Modin installed. I requested from CI team to make an environment with Modin, along with env creation instructions, but have no update that this has been made

2020-10-06 15:33 UTC, raoberman commented
@anjgola @JoeOster  please run test again, added env creation instructions

2020-10-06 16:20 UTC, JoeOster submitted a review, later dismissed
Kicking off ci again

2020-10-06 20:19 UTC, raoberman commented
@JoeOster @anjgola please initiate ci again, i modified the install instructions even though not sure why it failed (ran perfectly fine on my machine and DevCloud fresh install).

2020-10-07 18:22 UTC, raoberman commented
@JoeOster @anjgola please initiate ci again, i modified the install instructions even though not sure why it failed (ran perfectly fine on my machine and DevCloud fresh install).

2020-10-07 20:53 UTC, JoeOster commented
> @JoeOster @anjgola please initiate ci again, i modified the install instructions even though not sure why it failed (ran perfectly fine on my machine and DevCloud fresh install).

I have requested it to be run again

2020-10-07 21:11 UTC, raoberman commented
> > @JoeOster @anjgola please initiate ci again, i modified the install instructions even though not sure why it failed (ran perfectly fine on my machine and DevCloud fresh install).
> 
> I have requested it to be run again

Thank you @JoeOster for your help, much appreciated :)

2020-10-08 14:52 UTC, anjgola approved these changes

2020-10-08 15:05 UTC, JoeOster approved these changes
approving for ci

2020-10-08 16:39 UTC, JoeOster approved these changes
approving for ci

2020-10-09 13:09 UTC, raoberman commented
@malikabhi @sravanikonda  please approve to reinitiate CI validation. Thank you

2020-10-09 20:03 UTC, JoeOster approved these changes

2020-10-12 15:29 UTC, raoberman commented
@JoeOster fixed the Modin sample.json issue and validated in JSONLint. please initiate CI validation (hopefully last time :) ) thanks in advanced

2020-10-12 15:46 UTC, JoeOster approved these changes

2020-10-12 19:06 UTC, raoberman commented
@JoeOster @malikabhi @sravanikonda CI tests passed! please approve merge.  thanks in advanced

2020-10-12 19:18 UTC, merged