Rewrite of Max Interleaving Code Sample So That Interleaving Is Possible
oneapi-src/oneAPI-samples pull request #1876
Opened 2023-09-05 14:17 UTC by fredderf121

# Existing Sample Changes
## Description

The loops in the old code sample had memory dependencies that prevented interleaving from occurring and relied on the compiler's inability to analyze memory dependencies to demonstrate the area savings of interleaving. 
An upcoming internal compiler PR improves our compiler's analysis abilities, rendering the old sample obsolete. 

As such, the code sample has been modified to contain loops that support interleaving. The README.md has been updated with the new hardware runtime data and some structural changes, as the old README.md frequently stated how the loops did not support interleaving, which is no longer the case.

Fixes Issue# N/A

## External Dependencies

N/A

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line (CMake - note that aside from one additional warning flag, I did not modify `CMakeLists.txt`, nor change how the sample was compiled)
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compiler flag "-Wall -Wformat-security -Werror=format-security" was used

2023-09-05 14:36 UTC, yuguen-intel requested changes

2023-09-05 14:36 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/README.md
> +| Cycle | Stage 1 | Stage 2 | Stage 3 | Stage 4 | Stage 5 |
Please align the tables in the textual form for people reading the README in a text editor

2023-09-06 07:22 UTC, yuguen-intel submitted a review, later dismissed

2023-09-06 13:21 UTC, yuguen-intel requested changes
Must target the development branch

2023-09-06 14:09 UTC, fredderf121 commented
Created new PR to target development. https://github.com/oneapi-src/oneAPI-samples/pull/1879

2023-09-06 14:09 UTC, closed without merging