Add new sample: component_interfaces_comparison
oneapi-src/oneAPI-samples pull request #1878
Opened 2023-09-05 16:09 UTC by KevinUTAT

# Adding a New Sample(s)

## Description

This sample introduces different invocation/data interfaces that can be used in IP Authoring flow

## Testing

Regtest link coming soon

## Checklist
Administrative
- [x] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [x] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [x] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [x] Adhere to readme template 
- [x] Enforce format via clang-format config file
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2023-09-06 07:23 UTC, yuguen-intel approved these changes

2023-09-06 15:40 UTC, pmpeter1 requested changes

2023-09-06 15:40 UTC, pmpeter1 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/streaming-invocation/src/vector_add.cpp
> +#define VECT_SIZE 256
Should avoid usage of #define in C++ and try to use a typesafe alternative like constexpr

2023-09-06 15:40 UTC, pmpeter1 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/pipes/src/vector_add.cpp
> +#define VECT_SIZE 256
Should avoid #define in C++ and prefer typesafe alternatives like constexpr

2023-09-06 15:40 UTC, pmpeter1 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/naive/src/vector_add.cpp
> +#define VECT_SIZE 256
Should avoid #define in C++ and use typesafe alternatives

2023-09-06 15:40 UTC, pmpeter1 commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/csr-pipes/src/vector_add.cpp
> +#define VECT_SIZE 256
Should avoid #define in C++

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/csr-pipes/src/vector_add.cpp
> +#define VECT_SIZE 256
```suggestion
constexpr int kVectorSize = 256;
```

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/csr-pipes/src/vector_add.cpp
> +    int count = VECT_SIZE;  // pass array size by value
```suggestion
    int count = kVectorSize;  // pass array size by value
```

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/mm-host/src/vector_add.cpp
> +#define VECT_SIZE 256
```suggestion
constexpr int kVectorSize = 256;
```

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/mm-host/src/vector_add.cpp
> +    int count = VECT_SIZE;  // pass array size by value
```suggestion
    int count = kVectorSize;  // pass array size by value
```

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/naive/src/vector_add.cpp
> +#define VECT_SIZE 256
```suggestion
constexpr int kVectorSize = 256;
```

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/naive/src/vector_add.cpp
> +    int count = VECT_SIZE;  // pass array size by value
```suggestion
    int count = kVectorSize;  // pass array size by value
```

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/pipes/src/vector_add.cpp
> +#define VECT_SIZE 256
```suggestion
constexpr int kVectorSize = 256;
```

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/pipes/src/vector_add.cpp
> +    int count = VECT_SIZE;  // pass array size by value
```suggestion
    int count = kVectorSize;  // pass array size by value
```

2023-09-07 06:30 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/streaming-invocation/src/vector_add.cpp
> +#define VECT_SIZE 256
```suggestion
constexpr int kVectorSize = 256;
```

2023-09-09 17:44 UTC, ishaghosh27 approved these changes

2023-09-12 07:47 UTC, merged