Lqnguyen branch1
oneapi-src/oneAPI-samples pull request #201
Opened 2020-10-01 02:01 UTC by lqnguyen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue) 

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [ ] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [ ] Implement coding guidelines and ensure code quality.
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [ ] Adhere to readme template 
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Enforce format via clang-format config file
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [ ] Tested using Dev Cloud when applicable
- [ ] Implement fixes for ONSAM Jiras
- [ ] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

2020-10-01 14:41 UTC, pmpeter1 requested changes
If you have "using std" in the code you should not also have std:: unless it's to resolve an ambiguity.

It works best to design your kernels inside-out.   I.e. figure out how to represent the inner loop best, and use the most obvious names (should not need _acc suffixes), then name your buffers, then name your data objects.   

The breaking of strings at likes 132-135 should be fixed to be more natural.

At 208, this is not Kernel time this is more elapsed time.  It includes data transfer cost and other overhead not just kernel execution time on the device.

2020-10-01 19:17 UTC, JoeOster requested changes

2020-10-01 19:17 UTC, JoeOster commented on DirectProgramming/DPC++/ParallelPatterns/PrefixSum/src/PrefixSum.cpp
>      std::cout << a[i] << " ";
redundant std:: as you are already using the std namespace

2020-10-02 00:19 UTC, lqnguyen commented
Source file has been updated based on comments. Please review.

2020-10-02 03:58 UTC, JoeOster requested changes
std:: is not necessary when using the std namespace unless it is to avoid confusion, please remove the extra

2020-10-02 03:59 UTC, JoeOster requested changes
std:: is not necessary when using the std namespace unless it is to avoid confusion, please remove the extra

2020-10-02 16:44 UTC, pmpeter1 requested changes
The exception handler should be from dpc_common.hpp.

The Usage() function should restructure the strings to look better when formatted with clang-format.   Clean up where line-breaks are made by the formatter.

2020-10-02 19:25 UTC, pmpeter1 approved these changes

2020-10-02 21:22 UTC, JoeOster approved these changes

2020-10-02 21:22 UTC, merged