Update READMEs with new template for IntelPyTorch Inference/Training Optimizations
oneapi-src/oneAPI-samples pull request #2305
Opened 2024-04-26 19:05 UTC by alexsin368

# Existing Sample Changes
## Description

Update READMEs according to new template: https://github.com/oneapi-src/oneAPI-samples/wiki/AI-Getting-Started-and-Features-and-Functionality-README-Template

Fixes Issue# N/A

## External Dependencies

None

## Type of change

Just README update

## How Has This Been Tested?

Testing not needed for README update since only formatting changed.

2024-05-02 16:36 UTC, Marina-Zubova requested changes
Thank you for updating the READMEs, I left some comments

2024-05-02 16:36 UTC, Marina-Zubova commented on AI-and-Analytics/Features-and-Functionality/IntelPyTorch_InferenceOptimizations_AMX_BF16_INT8/README.md
in AI template, there is a note under the table
```suggestion
> **Note**: AI and Analytics samples are validated on AI Tools Offline Installer. For the full list of validated platforms refer to [Platform Validation](https://github.com/oneapi-src/oneAPI-samples/tree/master?tab=readme-ov-file#platform-validation).
```

2024-05-02 16:39 UTC, Marina-Zubova requested changes

2024-05-02 16:39 UTC, Marina-Zubova commented on AI-and-Analytics/Features-and-Functionality/IntelPyTorch_TrainingOptimizations_AMX_BF16/README.md
in AI template, there is a not under the table
```suggestion
> **Note**: AI and Analytics samples are validated on AI Tools Offline Installer. For the full list of validated platforms refer to [Platform Validation](https://github.com/oneapi-src/oneAPI-samples/tree/master?tab=readme-ov-file#platform-validation).
```

2024-05-02 16:40 UTC, Marina-Zubova commented on AI-and-Analytics/Features-and-Functionality/IntelPyTorch_TrainingOptimizations_AMX_BF16/README.md
```suggestion
*Other names and brands may be claimed as the property of others. [Trademarks](https://www.intel.com/content/www/us/en/legal/trademarks.html)
```

2024-05-15 00:59 UTC, alexsin368 commented on AI-and-Analytics/Features-and-Functionality/IntelPyTorch_TrainingOptimizations_AMX_BF16/README.md
My mistake. Just fixed it.

2024-06-04 23:24 UTC, Marina-Zubova approved these changes

2024-06-05 20:42 UTC, merged