[FPGA] Remove mandatory DEVICE_FLAG from mem_channel tutorial
oneapi-src/oneAPI-samples pull request #2322
Opened 2024-05-05 01:26 UTC by justin-rosner

## Description

This change removes the fatal error when the user does not specify the DEVICE_FLAG when compiling. The motivation behind this change is that even when users specify the correct DEVICE_FLAG, they will get a cmake warning telling them that DEVICE_FLAG was unused. 

## External Dependencies

* N/A

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Manually compiled the design to reports to make sure that the cmake warning is no longer displayed to users.

2024-05-06 15:01 UTC, whitepau requested changes
I don't think you can just unilaterally remove this check, since the `DEVICE_FLAG` variable is checked on line 71 of the CMakeLists.txt.

2024-05-07 17:57 UTC, justin-rosner commented
> I don't think you can just unilaterally remove this check, since the `DEVICE_FLAG` variable is checked on line 71 of the CMakeLists.txt.

It looks like this is a documented CMake issue: https://gitlab.kitware.com/cmake/cmake/-/issues/18152. As such, I'm not sure if there is anything that we can do to our code sample to account for this while still keeping the functional behaviour the same. Do you think it is acceptable to have this warning be emitted when users are compiling for unknown boards, e.g. the new Arrow Creek boards?

2024-05-08 08:22 UTC, whitepau commented
you can just put the check before line 71 so it only happens just before the CMake script tries to use `DEVICE_FLAG`.

If you want the check to happen universally, then i suppose the warning is not a big deal.

2024-05-08 13:15 UTC, justin-rosner commented
> you can just put the check before line 71 so it only happens just before the CMake script tries to use `DEVICE_FLAG`.
> 
> If you want the check to happen universally, then i suppose the warning is not a big deal.

I still think that we want the check to happen universally, so I'll just update the regtest and close out this PR. Thanks Paul.

2024-05-08 20:11 UTC, justin-rosner commented
I've reopened this as it turns out that this was not a bug in CMake but rather due to the fact that `-DDEVICE_FLAG` was never being used if it was passed in conjunction with `-DDPART=INTERLEAVING`. This new if-else logic covers all of the old cases, while avoiding the unused variable warning.

2024-05-10 08:38 UTC, whitepau commented
Does printing the value of `DEVICE_FLAG` also silence the warning?

2024-05-10 14:09 UTC, whitepau approved these changes
short and sweet

2024-05-10 14:11 UTC, yuguen-intel approved these changes

2024-05-10 14:11 UTC, merged