Replaced single_task reduction to parallel reduction and updated sample as per latest coding guidelines
oneapi-src/oneAPI-samples pull request #238
Opened 2020-10-13 05:01 UTC by mpanoop

# Replaced single_task reduction to parallel reduction and updated code to latest coding guidelines

1. Previously there was a third kernel which was exclusively doing serial reduction of the energy array whose memory footprint was "n" (number of particles) and this array was memory synchronized for iteration between CPU and GPU. Updated the sample to support parallel reduction and hence the third kernel is removed and the reduction operation is integrated to the second kernel. Also the memory footprint of the same is reduced to a scalar float instead of an array of "n" elements.

2. Accessor returned from a buffer using get_access is by default access::mode::read_write. So updated the sample to remove the explicit mention of this access mode.

3. Updated the README.md to reflect the parallel reduction feature in DPC++.

Fixes # (issue) 

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ X ] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [ ] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [ ] Implement coding guidelines and ensure code quality.
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [ ] Adhere to readme template 
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Enforce format via clang-format config file
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [ ] Tested using Dev Cloud when applicable
- [ ] Implement fixes for ONSAM Jiras
- [ ] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

2020-10-13 15:05 UTC, JoeOster submitted a review, later dismissed
approving for kicking off ci

2020-10-13 16:05 UTC, pmpeter1 requested changes

2020-10-13 16:05 UTC, pmpeter1 commented on DirectProgramming/DPC++/N-BodyMethods/Nbody/src/GSimulation.cpp
>         auto p = pbuf.get_access<access::mode::read_write>(h);
Need new SYCL 2020 form of accessor.

2020-10-13 23:20 UTC, mpanoop commented on DirectProgramming/DPC++/N-BodyMethods/Nbody/src/GSimulation.cpp
> +  RealType *energy = (RealType *)malloc_shared(sizeof(RealType),q);
Fixed this in latest code

2020-10-13 23:20 UTC, mpanoop commented on DirectProgramming/DPC++/N-BodyMethods/Nbody/src/GSimulation.cpp
>         auto p = pbuf.get_access<access::mode::read_write>(h);
Fixed this in latest code.

2020-10-13 23:22 UTC, JoeOster approved these changes
approving to launch ci

2020-10-14 14:24 UTC, anjgola approved these changes

2020-10-14 14:24 UTC, merged