[FPGA] Remove reference to hardware runs on Windows
oneapi-src/oneAPI-samples pull request #2419
Opened 2024-08-01 19:01 UTC by justin-rosner

## Description

This PR removes reference in the code samples to hardware runs on Windows as this is not something that is supported.

## External Dependencies

* N/A

## Type of change 

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

* These are just removing references in our code samples to running hardware jobs on windows.

2024-08-13 09:04 UTC, whitepau requested changes
Hi Justin,

Sorry I was so slow to get this review out to you. A few of the readmes use a different format and I'd like that straightened out.

2024-08-13 09:04 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md
Add this note for the `### On Linux` section:

> **Note**: Running this sample on an actual FPGA device requires a BSP that supports host pipes. As there are currently no commercial BSPs with such support, only the SYCL HLS flow is enabled for this code sample.

2024-08-19 11:35 UTC, whitepau approved these changes

2024-08-22 14:31 UTC, jimmytwei approved these changes

2024-08-22 14:31 UTC, merged