FPGA: Adding a New Sample: `memory_system`
oneapi-src/oneAPI-samples pull request #2476
Opened 2024-09-04 14:28 UTC by haoyanwa

# Adding a New Sample: `memory_system`

## Description

This code sample demonstrates how to implement an efficient banked memory system. We show the users how to partition the memory system, the effect that memory access has to the system performance, how to mitigate bad memory access/layout, and how the compiler optimizes memory banks.

## Checklist
Administrative
- [x] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [x] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [x] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [x] Adhere to readme template 
- [x] Enforce format via clang-format config file
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [x] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [x] FPGA Regtest (Linux) https://spetc.intel.com/testanalysis?trview=0&testRunIds=10661780
- [x] FPGA Regtest (Windows) https://spetc.intel.com/testanalysis?trview=5&runBy=85740096&runBy_reporting_eng=true&testRunIds=10698400&tapgsize=1500

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [x] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [x] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2024-09-04 15:54 UTC, whitepau reviewed
alternative screenshots for waveforms that are a bit easier to read

2024-09-04 15:54 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/assets/waveform_naive.png
![naive](https://github.com/user-attachments/assets/38d8a880-3972-445b-a1ab-f1bd4dd7aa45)

2024-09-04 15:54 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/assets/waveform_optimized.png
![optimized](https://github.com/user-attachments/assets/eed8eb3a-c6eb-47a6-ba4c-8d26642aa630)

2024-09-05 07:44 UTC, whitepau approved these changes

2024-09-10 22:30 UTC, tomlenth approved these changes
Another thorough readme.  thx.

2024-09-20 12:49 UTC, yuguen-intel requested changes

2024-09-20 12:49 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/README.md
> +   |:---                 |:---
This is not in line with the rest of the samples readmes

2024-09-20 12:49 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/src/main.cpp
> +class ID_NaiveKernel;
There should be no `_` in class names
`IDNaiveKernel`

2024-09-20 12:49 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/src/main.cpp
> +  SimpleOutputT resultNaive;
variable names should be snake_case: `result_naive`

2024-09-20 12:49 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/src/main.cpp
> +}
no return?

2024-09-20 12:49 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/src/memory_system_defines.hpp
> +class ID_InStream_NaiveKernel;
CamelCase

2024-09-20 12:49 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/src/memory_system_defines.hpp
> +using InStream_NaiveKernel =
CamelCase

2024-09-20 12:49 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/src/memory_system_kernels.hpp
> +      OutStream_NaiveKernel::write(output);
```suggestion
      OutputStreamNaiveKernel::write(output);
```

2024-09-20 14:27 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/banked_memory_system/src/memory_system_kernels.hpp
> +      OutStream_NaiveKernel::write(output);
Sorry I meant `OutSteamNaiveKernel`

2024-09-27 13:08 UTC, yuguen-intel approved these changes

2024-09-27 13:09 UTC, merged