Update all READMEs with Windows support to include Windows 11
oneapi-src/oneAPI-samples pull request #2492
Opened 2024-09-20 02:58 UTC by yeetengangIntel

# Existing Sample Changes
## Description

This changes updated the READMEs with Windows* or Windows* 10 support to include Windows 11 support as well. 

Fixes Issue# [ONSAM-2002](https://jira.devtools.intel.com/browse/ONSAM-2002)

## External Dependencies

None.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ X] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

2024-09-24 15:42 UTC, jimmytwei commented
@yuguen-intel Can you look at the FPGA READMEs? As part of UAT we found that the sample READMEs aren't mentioning Windows 11 and @yeetengangIntel has updated all of the FPGA READMEs and other code samples to include them. Let me know if that's fine.

2024-09-24 16:04 UTC, yuguen-intel requested changes
This is missing the newly added svd Reference design 
https://github.com/oneapi-src/oneAPI-samples/tree/development/DirectProgramming/C%2B%2BSYCL_FPGA/ReferenceDesigns)
/svd

2024-09-25 02:29 UTC, fongjiantan commented
@yuguen-intel The SVD README has been updated to mention Windows 11 support

2024-09-25 07:50 UTC, yuguen-intel approved these changes

2024-09-25 14:17 UTC, jimmytwei approved these changes

2024-09-25 14:17 UTC, merged