Update -mkl -> -qmkl compiler flag for 2021.2
oneapi-src/oneAPI-samples pull request #438
Opened 2021-03-09 18:45 UTC by petercad

This MR updates the oneMKL samples for compatibility with **2021.2 only**. There is a breaking change in the compiler flags for linking oneMKL (was `-mkl`, now `-qmkl`) between 2021.1 and 2021.2. Hence, CI is expected to fail.

This MR is intended for use with the 2021.2 tag. I'll open a separate MR that makes the samples compatible with both 2021.1 and 2021.2 for use in the master branch, at the expense of more complicated makefiles.

Also fixes some compile errors in `monte_carlo_{pi,european_opt}` due to a missing `#include`.

FYI: @JoeOster

2021-03-09 20:12 UTC, JoeOster approved these changes
approving for ci to run

2021-03-10 16:59 UTC, JoeOster requested changes
We need to fix the following:
Add a comment about 

- the changes between 2021.1 and 2021.2 within the readme
- add some logic to the makefile to output useful guidance if the link fails, something like: "Build was not successful. Make sure you are using oneAPI 2021.2 or newer and have initialized the oneAPI environment using setvars.sh."

2021-03-15 00:22 UTC, JoeOster commented
@petercad - please update the sample, as you have a bunch of conflicts

2021-03-15 15:05 UTC, petercad commented
@JoeOster Yes, these are conflicts against #439. Let me close this PR for now, and I will reopen it with necessary changes after 2021.2 is ready.

2021-03-15 15:07 UTC, closed without merging