Update oneVPL import lib name in solution file
oneapi-src/oneAPI-samples pull request #441
Opened 2021-03-10 22:56 UTC by mav-intel

This is coupled with 2021.2.2 component release.

# Description

Import lib name has been changed for oneVPL 2021.2.2.  This impacts solution files since they require explicit file names to find libraries as opposed to using package configuration methods.

Fixes # VPL7-1035

# How Has This Been Tested?

- [x] Visual Studio

2021-03-12 00:35 UTC, JoeOster requested changes
Note: Per conversation with Marc, further changes are needed

2021-03-12 05:08 UTC, jonrecker commented on Libraries/oneVPL/dpcpp-blur/src/dpcpp-blur.cpp
> +                break;
Also need to call MFXDispReleaseImplDescription each time through the loop.

2021-03-15 00:26 UTC, JoeOster commented
currently running into launching CI, error message as follows:, Snapshot dependency canceled: ... pre-execution checks

 merging as I believe its fine and we need it merged for PV

2021-03-15 00:26 UTC, JoeOster approved these changes

2021-03-15 00:26 UTC, merged