Dnnl vtune
oneapi-src/oneAPI-samples pull request #504
Opened 2021-05-14 01:22 UTC by louie-tsai

# Introduction
This template serves 2 purposes and will need to be edited accordingly prior to submitting the PR

- Submission of new Samples

## External Dependencies

pandas and matplotlib

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X ] Command Line

# Adding a New samples
##Introduction
This new tutorial will guide you how to optimize a pre-trained model for a better inference performance, and also analyze the model pb files before and after the inference optimizations

## Checklist
Administrative
- [ X] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [X ] If you dependencies/binaries, inform the oneAPI Code Samples Project Manager: @JoeOster

Code Development
- [ X] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ X] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [X ] OSPDT Approval (see @JoeOster for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ X] Protex (see @JoeOster for assistance)
- [ ] Bandit Scans (Python only)
- [ X] IPLDT Scan (see @JoeOster for assistance)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Joe Oster(@JoeOster)
- [ ] Tested using Dev Cloud when applicable

2021-05-14 02:05 UTC, louie-tsai commented
attached a pdf with results from previous run.
[tutorial_vtune_profiling_0512.pdf](https://github.com/oneapi-src/oneAPI-samples/files/6476065/tutorial_vtune_profiling_0512.pdf)

2021-05-14 18:31 UTC, JoeOster commented
@louie-tsai PR description has been updated

2021-05-14 18:40 UTC, JoeOster commented
Which domain expert did you use to review this with? Put it in the first line for the Admin checklist

2021-05-17 22:00 UTC, louie-tsai commented
> Which domain expert did you use to review this with? Put it in the first line for the Admin checklist

I put name in the checklist, and I forwarded this MR to those oneDNN exports.

2021-05-17 22:38 UTC, JoeOster requested changes
Please take a look at yout TM and branding, oneDnn has specific rules

- The following names are allowed based on guidelines from Intel Legal (see namesdb.intel.com for more details)
    - oneDNN after oneAPI Deep Neural Network Library (oneDNN)

I sent you the TM&Branding report, please use that to look at anything that was flagged

2021-05-18 19:17 UTC, JoeOster requested changes
Line#1 - Please add the "®" symbol after Intel
Line#3 - Please add the "®" symbol after Intel -
Note the first instance of Intel per heading style must include a "®" subsequent "Intel" do not
Line #3 does any of this apply?
The following names are allowed based on guidelines from Intel Legal (see namesdb.intel.com for more details)
Compute Library for Deep Neural Networks
Intel® Math Kernel Library for Deep Neural Networks
Intel Math Kernel Library for Deep Neural Networks after Intel® Math Kernel Library for Deep Neural Networks

Fixing these issues fulfill the IPLDT requirements

2021-05-18 19:17 UTC, JoeOster commented on Libraries/oneDNN/tutorials/README.md
> +| Component | [vtune profiling](tutorial_vtune_profiling.ipynb) | This Jupyter Notebook demonstrates how to use VTune Profiler to profile oneDNN samples and find out performance bottlenecks. |
vtune should have Intel in front of it on first use. 
Please add the "™" symbol after VTune

all instances of vtune, should be VTune unless used in a path

2021-05-19 17:21 UTC, louie-tsai commented
@dmitryryintel
the memory bound number seems to be strange due to short profiling time.
Louie plans to make the samples run longer and then get the results again.

2021-05-20 21:59 UTC, JoeOster submitted a review, later dismissed
approved for ci

2021-05-20 23:28 UTC, louie-tsai commented
> @dmitryryintel
> the memory bound number seems to be strange due to short profiling time.
> Louie plans to make the samples run longer and then get the results again.

execute 20 times instead of 1 time to have more samples for profiling.
here is the result.
[tutorial_vtune_profiling - Jupyter Notebook.pdf](https://github.com/oneapi-src/oneAPI-samples/files/6519171/tutorial_vtune_profiling.-.Jupyter.Notebook.pdf)

2021-05-22 00:42 UTC, louie-tsai commented
@JoeOster 

I couldn't reproduce the issue on my environment, and I got good result for "runipy tutorial_vtune_profiling.ipynb".
Can I get those output files like hotspot.csv from CI run?

regards
Louie

2021-05-22 06:09 UTC, JoeOster submitted a review, later dismissed
approving for ci only

2021-05-24 21:53 UTC, louie-tsai commented
@JoeOster 
Added error handlings for the ci testing issues.
please help me to re-test it.

2021-05-25 19:22 UTC, JoeOster approved these changes
approve for ci

2021-05-26 05:13 UTC, louie-tsai commented
some system reqs for this VTune profiling.
/proc/sys/kernel/perf_event_paranoid needs to be set as 0.

2021-05-26 14:46 UTC, louie-tsai commented
@JoeOster 
please help me to merge the PR if all look good to you.

thanks

2021-05-26 15:10 UTC, merged