XGBoost 2 features samples
oneapi-src/oneAPI-samples pull request #509
Opened 2021-05-17 14:33 UTC by raoberman

# Introduction
This template serves 2 purposes and will need to be edited accordingly prior to submitting the PR
- Changes to existing samples
- Submission of new Samples

# Existing Sample Changes
## Description

Added 2 new samples to XGBoost including README and sample.json

# Adding a New samples
##Introduction

The full instructions on submitting a new sample is located in the [wiki](https://github.com/oneapi-src/oneAPI-samples/wiki/Contributing-a-New-Sample) if you have any addional questions contact @JoeOster

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you dependencies/binaries, inform the oneAPI Code Samples Project Manager: @JoeOster

Code Development
- [X] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [X] Adhere to readme template 
- [X] Enforce format via clang-format config file
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [X] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [] OSPDT Approval (see @JoeOster for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Protex (see @JoeOster for assistance)
- [X] Bandit Scans (Python only)
- [ ] IPLDT Scan (see @JoeOster for assistance)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Joe Oster(@JoeOster)
- [X] Tested using Dev Cloud when applicable

2021-05-17 14:34 UTC, raoberman commented
@JoeOster please conduct IP scan and anything else @tomlenth @JoeOster please conduct README review

2021-05-17 18:02 UTC, JoeOster requested changes
I made some minor edits, please review and alter as needed

2021-05-17 18:17 UTC, raoberman commented on AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_Performance/README.md
> +| OS                                | 64-bit Linux: Ubuntu 18.04 or higher, 64-bit Windows 10, macOS 10.14 or higher
the sample can be run for all OS systems, but AI Kit is only available on Linux. hence the discrepancy. I can remove the other 2 OS depending on your judgement.

2021-05-17 18:17 UTC, raoberman commented on AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_daal4pyPrediction/README.md
> +| OS                                | 64-bit Linux: Ubuntu 18.04 or higher, 64-bit Windows 10, macOS 10.14 or higher
the sample can be run for all OS systems, but AI Kit is only available on Linux. hence the discrepancy. I can remove the other 2 OS depending on your judgement.

2021-05-17 18:25 UTC, JoeOster commented on AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_daal4pyPrediction/README.md
> +| OS                                | 64-bit Linux: Ubuntu 18.04 or higher, 64-bit Windows 10, macOS 10.14 or higher
Yes please remove, unless your going to add install instructions for Darwin and Windows

2021-05-17 18:25 UTC, JoeOster commented on AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_Performance/README.md
> +| OS                                | 64-bit Linux: Ubuntu 18.04 or higher, 64-bit Windows 10, macOS 10.14 or higher
Yes please remove, unless your going to add install instructions for Darwin and Windows

2021-05-17 18:59 UTC, JoeOster commented
As you have this marked as pytrhon, I will need a bandit scan of the python files

2021-05-17 19:01 UTC, raoberman commented
> As you have this marked as pytrhon, I will need a bandit scan of the python files

I already ran Bandit scans on these prior to submitting PR. Both came up with 0 issues or vulnerabilities.

2021-05-17 22:56 UTC, tomlenth reviewed
Can this sample be run in the devlcoud?  If so, it probably needs the content specific to selecting a node.  Running Samples In DevCloud
If running a sample in the Intel DevCloud, remember that you must specify the compute node (CPU, GPU, FPGA) and whether to run in batch or interactive mode. For more information, see the Intel® oneAPI Base Toolkit Get Started Guide (https://devcloud.intel.com/oneapi/get-started/base-toolkit/)

2021-05-17 23:52 UTC, raoberman commented
@tomlenth this sample can be run on DevCloud - I used ai kit JupyterLab which by default is CPU node

2021-05-20 20:59 UTC, raoberman commented on AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_daal4pyPrediction/README.md
> +| OS                                | 64-bit Linux: Ubuntu 18.04 or higher, 64-bit Windows 10, macOS 10.14 or higher
done

2021-05-20 21:56 UTC, JoeOster approved these changes
approved for ci to run

2021-05-21 14:42 UTC, raoberman commented
@JoeOster try again to run CI. Is runipy installed by default as part of base env ai kit? I recall some conversation around that for sample CI issues like this....

2021-05-21 15:30 UTC, JoeOster approved these changes
approved for ci only

2021-05-21 17:22 UTC, raoberman commented
@JoeOster fixed the strange errors. approve to run CI again please

2021-05-21 17:31 UTC, JoeOster approved these changes
approved for ci only

2021-05-25 20:45 UTC, JoeOster submitted a review, later dismissed
approved for ci only testing

2021-05-26 01:42 UTC, raoberman commented
@JoeOster please approve. trying a new ci sample.json method.

2021-05-26 15:06 UTC, raoberman commented
@mdbtucker  please approve for CI run

2021-05-26 15:08 UTC, JoeOster submitted a review, later dismissed
approved for ci

2021-05-26 15:25 UTC, JoeOster submitted a review, later dismissed
approved for ci

2021-05-26 15:48 UTC, raoberman commented
@JoeOster @mdbtucker please approve for ci run (this may be it)!

2021-05-26 16:09 UTC, JoeOster approved these changes
approved for ci

2021-05-26 16:41 UTC, merged