Creating a new FPGA reference design: Merge Sort
oneapi-src/oneAPI-samples pull request #565
Opened 2021-06-25 14:58 UTC by tyoungsc

# Adding a New Sample(s)
## Description
This new FPGA reference design is a merge sort design that utilizes the FPGAs spatial computation using thread- and SIMD-level parallelism.

## Checklist
Administrative
- [X] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): @mdbtucker
- [X] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager: @JoeOster

Code Development
- [X] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [X] Adhere to readme template 
- [X] Enforce format via clang-format config file
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see @JoeOster for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Joe Oster(@JoeOster)
- [ ] Tested using Dev Cloud when applicable

2021-06-25 15:22 UTC, JoeOster commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/README.md
> +| OS                                | Linux* Ubuntu* 18.04/20.04, RHEL*/CentOS* 8, SUSE* 15; Windows* 10
Remove Linux or add a comma

2021-06-28 13:39 UTC, mdbtucker submitted a review, later dismissed

2021-06-28 14:06 UTC, pmpeter1 requested changes

2021-06-28 14:06 UTC, pmpeter1 commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/src/main.cpp
> +    return 0;
The failure return code should be != 0.

2021-06-28 14:06 UTC, pmpeter1 commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/src/sorting_networks.hpp
> +#define SWAP(a, b)  \
Why use a macro rather than an inline function?

2021-06-29 00:12 UTC, tomlenth submitted a review, later dismissed
no issues.  thanks

2021-06-29 14:20 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/src/main.cpp
> +    return 0;
fixed

2021-06-29 14:20 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/src/main.cpp
> +  runs = std::max((int)2, runs);
Made it an error instead.

2021-06-29 14:25 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/README.md
> +| OS                                | Linux* Ubuntu* 18.04/20.04, RHEL*/CentOS* 8, SUSE* 15; Windows* 10
Done

2021-06-29 19:35 UTC, mdbtucker submitted a review, later dismissed

2021-06-29 20:32 UTC, JoeOster reviewed
I didn't see any third-party components, did I miss any?

2021-06-29 21:25 UTC, mdbtucker commented
> I didn't see any third-party components, did I miss any?

No, you didn't miss any, there are no third party components in this design.

2021-07-05 14:59 UTC, tyoungsc commented
@pmpeter1 I addressed your three comments. When you get the chance, can you verify that the changes are sufficient?

2021-07-06 15:59 UTC, pmpeter1 approved these changes

2021-07-06 17:27 UTC, tyoungsc commented
Sorry @mdbtucker and @pmpeter1: I found two functions which didn't match the proper style guidelines and changed them.

2021-07-06 18:26 UTC, mdbtucker approved these changes

2021-07-06 18:42 UTC, merged