Update OpenMP Training
oneapi-src/oneAPI-samples pull request #580
Opened 2021-07-08 23:04 UTC by strongwar

# Existing Sample Changes
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Updated OpenMP Training for C++ and Fortran, added new sections for Host Device Concurrency, and Setting Target Device for Debugging. No added code, only added Markdown sections.

Fixes Issue# 

## External Dependencies

List any external dependencies created as a result of this change.
None

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [X] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

Ran Jupyter Notebooks on devcloud. Also compiled and ran code samples.

2021-07-12 15:05 UTC, JoeOster commented
@strongwar please review and fix your conflicts

2021-07-12 15:28 UTC, JoeOster commented
@strongwar This should have been 2 PRs as its 2 different subjects that I can identify so far. I am not sure I see the need for the new folder structures unless you have more sample changes coming 

Also for the new new DirectProgramming/Fortran/Jupyter/OpenMP_Offload_Fortran/OpenMP Welcome_Fortran.ipynb, you create a new folder for fortran and then call your sample...fortran, it becomes redundant.

@tomlenth do you have any feedback on the proposed folder structure from a UIx perspective

2021-07-14 21:53 UTC, strongwar commented
Reverted guid back to original
fix folders back to original structure

2021-07-20 17:25 UTC, JoeOster requested changes

2021-07-21 20:45 UTC, strongwar commented on DirectProgramming/C++/Jupyter/OpenMP-offload-training/OpenMP Welcome_C++.ipynb
> +{
Fixed the file names, back to original for C++ and Fortran

2021-07-27 20:35 UTC, JoeOster approved these changes

2021-08-13 16:02 UTC, JoeOster reviewed
This sample is missing some elements

No license file - for a MIT license, use https://github.com/oneapi-src/oneAPI-samples/blob/master/License.txt

2021-08-16 17:55 UTC, JoeOster commented
@tomlenth - Sample should require a Readme for each sample and none of the samples in this Jupyter folder has one, is this a miss or did we decide to skip it? The readme at the root is very generic and doesn't specify the samples contained...

2021-08-20 17:44 UTC, tomlenth requested changes
We definitely don’t need a readme for each sample given that it’s a jupyter notebook.  That said, it would be ideal to follow the exact format as the general DPC++ notebook, including the description of each directory. In addition, it’d be really nice to use the same directory naming convention with numbers to show the order. And, please add in the license mention.

2021-08-20 17:53 UTC, JoeOster requested changes
Per tom - We definitely don’t need a readme for each sample given that it’s a jupyter notebook. That said, it would be ideal to follow the exact format as the general DPC++ notebook, including the description of each directory. In addition, it’d be really nice to use the same directory naming convention with numbers to show the order. And, please add in the license mention.

2021-08-28 00:10 UTC, tomlenth approved these changes
would prefer that the directories are number like the other juypter trainings but can live with this for now.  will be more important to number as the number of directories increases since the material is meant to be consumed in a particular sequence.

2021-08-31 17:03 UTC, strongwar commented
Updated pdfs

2021-08-31 17:30 UTC, JoeOster approved these changes

2021-08-31 17:31 UTC, merged