Add Intel(R) Extension for Scikit-learn samples
oneapi-src/oneAPI-samples pull request #617
Opened 2021-08-12 01:59 UTC by PetrovKP

# Existing Sample Changes
## Description

Add Intel(R) Extension for Scikit-learn samples into AI-and-Analytics/Features-and-Functionality folder for migration

Fixes Issue# 

## External Dependencies

List any external dependencies created as a result of this change.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] New feature (non-breaking change which adds functionality)

# Adding a New Sample(s)

## Description

Please include a description of the sample

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager: @JoeOster

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see @JoeOster for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Joe Oster(@JoeOster)
- [ ] Tested using Dev Cloud when applicable

2021-08-12 10:28 UTC, PetrovKP commented
@outoftardis , @racheloberman-intel can you check PR?

2021-08-12 20:24 UTC, JoeOster submitted a review, later dismissed
approving for ci only

2021-08-12 21:48 UTC, tomlenth submitted a review, later dismissed

2021-08-19 15:48 UTC, outoftardis commented on AI-and-Analytics/Features-and-Functionality/IntelScikitLearn_Extensions_SVC_Adult/README.md
> +> NOTE: No action is required if users use Intel DevCloud as their environment.
```suggestion
> NOTE: No action is required if you are using Intel DevCloud as your environment.
```

2021-08-19 15:48 UTC, outoftardis commented on AI-and-Analytics/Features-and-Functionality/IntelScikitLearn_Extensions_SVC_Adult/README.md
> +  Please refer to [Intel oneAPI DevCloud](https://intelsoftwaresites.secure.force.com/devcloud/oneapi) for Intel DevCloud.
```suggestion
  Refer to [Intel oneAPI DevCloud](https://intelsoftwaresites.secure.force.com/devcloud/oneapi) for Intel DevCloud.
```

2021-08-23 23:16 UTC, JoeOster requested changes

2021-08-23 23:16 UTC, JoeOster commented on AI-and-Analytics/Features-and-Functionality/IntelScikitLearn_Extensions_SVC_Adult/README.md
> +If you are running this sample on the DevCloud, see [Running Samples on the Intel&reg; DevCloud](#run-samples-on-devcloud)
@PetrovKP - please provide the correct url of your choice

2021-08-24 16:34 UTC, JoeOster requested changes
As this is including a new dataset, I need information on this, name, URL and license

2021-08-24 17:10 UTC, JoeOster commented on AI-and-Analytics/Features-and-Functionality/IntelScikitLearn_Extensions_SVC_Adult/IntelScikitLearn_Extensions_SVC_Adult.py
> +# - Get speedup more than **72** times.
@outoftardis -Please note this comment is a little vague for me, please make changes as you require. Best method is to clone krills repo and make changes there. Then offer a PR to krill to accept. Please note everything I approved will need to be pulled into his repo, so you don't duplicate work. If questions about this process, please contact me via IM or @raoberman

2021-08-30 19:25 UTC, JoeOster submitted a review, later dismissed
approved for ci only

2021-08-30 19:32 UTC, JoeOster approved these changes
approved for ci only

2021-08-30 19:36 UTC, PetrovKP commented on AI-and-Analytics/Features-and-Functionality/IntelScikitLearn_Extensions_SVC_Adult/IntelScikitLearn_Extensions_SVC_Adult.ipynb
> +    "x, y = fetch_openml(name='a9a', return_X_y=True)"
Add reference for dataset

2021-08-30 19:36 UTC, PetrovKP commented on AI-and-Analytics/Features-and-Functionality/IntelScikitLearn_Extensions_SVC_Adult/IntelScikitLearn_Extensions_SVC_Adult.ipynb
> +   "cell_type": "markdown",
Added

2021-08-30 22:37 UTC, JoeOster approved these changes

2021-08-30 22:42 UTC, JoeOster requested changes
Pending OSPDT Approval

2021-09-03 22:54 UTC, JoeOster approved these changes

2021-09-03 22:54 UTC, merged