Rendering toolkit 05ispc sample addition PR
oneapi-src/oneAPI-samples pull request #800
Opened 2021-12-10 00:15 UTC by MichaelRoyceCarroll

# Adding a New Sample(s)

## Description

Introduce Intel ISPC compilation. ISPC is a new 2022.1 component in Rendering Toolkit.
Discussed in oneapi samples pxt brielfy (20211026 minutes)
Introduced in email thread with @MichaelRoyceCarroll @JoeOster YuryB and VadimS on 20211026.

This sample supports upcoming aims of oneAPI Rendering Toolkit Getting Started Guide. The guide will use this sample to introduce the ISPC component.

Original Source:

- https://github.com/ispc/ispc/tree/main/examples/cpu/simple

Original License:

- The sample is subject to the ISPC license on their github: https://github.com/ispc/ispc/blob/main/LICENSE.txt

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2021-12-10 00:19 UTC, MichaelRoyceCarroll commented
Looking for help on rebasing this PR properly. It doesn't look right. This should be one commit difference between oneapi-src:development and MichaelRoyceCarroll:RenderingToolkit-05ispc with my fork.... as of 20211209 4:19pm... not 69 commits!

Thanks,
-MichaelC

2022-01-14 18:23 UTC, MichaelRoyceCarroll commented
Performed rebase activity per Mike D B Tuckers guidance.

2022-01-14 18:34 UTC, praveenkk123 approved these changes
Approve for CI

2022-01-24 20:46 UTC, KanclerzPiotr approved these changes
Approve for CI

2022-01-25 16:31 UTC, tpyra requested changes

2022-01-25 16:31 UTC, tpyra commented on RenderingToolkit/GettingStarted/05_ispc_gsg/src/simple.cpp
> +  Copyright (c) 2010-2011, Intel Corporation
Is 2011 ok here?
```suggestion
  Copyright (c) 2010-2022, Intel Corporation
```

2022-03-07 17:06 UTC, praveenkk123 submitted a review, later dismissed

2022-03-08 00:19 UTC, MichaelRoyceCarroll commented on RenderingToolkit/GettingStarted/05_ispc_gsg/src/simple.ispc
> +  Copyright (c) 2010-2011, Intel Corporation
Praveen and Tomasz want the year updated. I will apply and resolve. Thanks.

2022-03-08 00:27 UTC, praveenkk123 approved these changes

2022-03-08 22:16 UTC, praveenkk123 approved these changes

2022-03-08 22:19 UTC, merged