update README.md for some missing links
oneapi-src/oneAPI-samples pull request #824
Opened 2022-01-13 01:25 UTC by louie-tsai

# Existing Sample Changes
## Description

Missing links in README.md. remove the links because no notebooks files in the repo. 
Instead, we ask users to copy notebooks from AI kit installation folder.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

2022-01-14 00:53 UTC, praveenkk123 submitted a review, later dismissed

2022-01-14 01:11 UTC, tomlenth commented on AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/README.md
> +These Jupyter notebooks help users analyze the performance benefit from using Intel Optimizations for Tensorflow with the oneDNN library.
Delete "These"

2022-01-14 01:11 UTC, tomlenth commented on AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/README.md
> +>Those notebooks are released with oneAPI AI Analytics Toolkit, and they are under the /opt/intel/oneapi/modelzoo/latest/models/docs/notebooks/perf_analysis folder.
Change "Those" to "The"

2022-01-14 01:13 UTC, tomlenth requested changes
Minor text changes per comments inline.

2022-02-01 22:53 UTC, tomlenth approved these changes

2022-02-01 22:54 UTC, praveenkk123 approved these changes

2022-02-01 22:55 UTC, merged