updated Welcome.ipynb and Readme to address ONSAM-1451 to include ste…
oneapi-src/oneAPI-samples pull request #899
Opened 2022-03-22 00:28 UTC by praveenkk123

…

# Existing Sample Changes
## Description

updated Welcome.ipynb and Readme to address ONSAM-1451 to include steps to run the notebooks locally and ONSAM-1450 to fix broken links in welcome.ipynb

Fixes Issue#
onsam-1450 and 1451

2022-03-22 01:07 UTC, tomlenth requested changes
Are the instructions to run locally specific to only Linux? unlike the typical sample readmes, it doesn't appear that we provide any OS compatibility.  the notebook readme's are really inconsistent and 1) I thought the AI samples are linux only and 2) if I'm not mistaken, getting the notebooks to run locally on windows requires jumping through hoops of fire.

2022-03-23 17:08 UTC, tomlenth approved these changes
Thanks Praveen!

2022-03-23 17:33 UTC, KanclerzPiotr approved these changes

2022-03-23 17:52 UTC, mdbtucker approved these changes
Approving based on Tom's review so this change can be comitted.  I have NOT reviewed this change.

2022-03-24 20:21 UTC, merged