FPGA: new reference design and linear algebra library - Cholesky-based matrix inversion
oneapi-src/oneAPI-samples pull request #953
Opened 2022-05-30 13:05 UTC by yuguen-intel

# Adding a New Sample

## Description

This pull request adds both:
- a new linear algebra header library (streaming_cholesky_inversion.hpp) that performs matrix inversions based on the Cholesky decomposition.
- a new reference design that exercises this new library.

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): @mdbtucker

Code Development
- [x] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [x] Adhere to readme template 
- [x] Enforce format via clang-format config file
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [x] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [x] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [x] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

2022-06-01 17:11 UTC, pmpeter1 requested changes

2022-06-01 17:11 UTC, pmpeter1 commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky_inversion/src/cholesky_inversion_demo.cpp
> +void generateInputData(std::vector<T> &a_matrix) {
Inconsistent naming convention for Function.

2022-06-01 17:11 UTC, pmpeter1 commented on DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky_inversion/src/cholesky_inversion_demo.cpp
> +int checkResults(std::vector<T> &a_matrix, std::vector<T> &i_matrix) {
Inconsistent naming convention for Function.

2022-06-01 22:54 UTC, tomlenth requested changes
the second paragraph with the reference to documentation has a couple of <br> tags.  these don't always render, but should be removed.

2022-06-02 07:05 UTC, yuguen-intel commented
@pmpeter1 thanks, fixed now
@tomlenth do you mean the <br> tags? These appear in all FPGA READMEs. If you think these should be removed, we can make a bulk change to all the FPGA READMEs rather than having it fixed it but not in the other ones?

2022-06-03 07:30 UTC, yuguen-intel commented
@tomlenth I'll do a bulk change then!
@praveenkk123 Can you have a look at this PR? It has been reviewed internally before, and I've manually validated it

2022-06-07 15:54 UTC, praveenkk123 approved these changes

2022-06-08 11:44 UTC, pmpeter1 approved these changes

2022-06-08 13:12 UTC, merged