Update mvdr_beamforming FPGA Reference Design to use shared include files
oneapi-src/oneAPI-samples pull request #985
Opened 2022-06-29 19:47 UTC by ericxu233

### Description
Update the FPGA mvdr_beamforming reference design to use code from the shared include directory.

* use shared library resources streaming_qrd.hpp, tuple.hpp, and unrolled_loop.hpp
* updated streaming_qrd.hpp to accept data in a different order, as required by the mvdr design

### Type of change
  
Code cleanup on an existing design.

### How Has This Been Tested?

* The mvdr_beamforming design has been compiled and ran on the FPGA emulator and results are passing.
* The mvdr_beamforming design has been compiled and ran on specific Intel FPGA boards. The executable output of the design shows that the code functionality is passing. 
  
### QoR Observations:
  
The design running on agilex has about double the fmax of the design running on stratix 10 but the throughput are roughly the same. In other words, the increase in fmax on agilex devices does not scale with the throughput. This behaviour is expected as @mdbtucker has identified the root cause of this issue to be related to board support packages.

2022-06-29 19:55 UTC, mdbtucker submitted a review, later dismissed
Already reviewed in PR to Eric's fork

2022-06-29 20:15 UTC, yuguen-intel requested changes

2022-06-29 20:15 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/include/streaming_qrd.hpp
> +                    // (reads the matrix one column at a time). Flase if read
```suggestion
                    // (reads the matrix one column at a time). False if read
```

2022-06-29 20:15 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/include/streaming_qrd.hpp
> +              true  // Defualt value is true for standard matrix input reads
```suggestion
              true  // Default value is true for standard matrix input reads
```

2022-06-29 20:15 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/include/streaming_qrd.hpp
> +      [[intel::fpga_memory]] [[intel::private_copies(
```suggestion
      [[intel::fpga_memory]]      // NO-FORMAT: Attribute
      [[intel::private_copies(2)]] // NO-FORMAT: Attribute
```

2022-06-29 20:15 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/include/streaming_qrd.hpp
> +          2)]]  // NO-FORMAT: Attribute
```suggestion

```

2022-06-29 20:19 UTC, yuguen-intel commented
This change looks very good, I just messaged you @ericxu233 regarding the testing that you did for that change :)
Thanks!

2022-07-06 07:12 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/include/streaming_qrd.hpp
> +      [[intel::fpga_memory]]
```suggestion
      [[intel::fpga_memory]] // NO-FORMAT: Attribute
```

2022-10-21 08:16 UTC, yuguen-intel approved these changes

2022-10-21 08:16 UTC, merged